
openapi: 3.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:

  /questions:
    post:
      tags: [Question Papers]
      summary: Import question paper (created_by taken from token)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            example:
              paper_name: "Math Test"
              level_id: 1
              set_id: 2
              duration: 60
              paper_type: "exam"
              status: "active"
              questions:
                - section: "A"
                  question_type: "mcq"
                  marks: 1
                  negative_marks: 0
                  question: "2 + 2 = ?"
                  option1: "1"
                  option2: "2"
                  option3: "4"
                  option4: "5"
                  correct_option: "option3"
                  explanation: "Basic math"
      responses:
        201:
          description: Created successfully

    /questions:
    get:
      tags: [Question Papers]
      summary: Get all question papers (only logged-in user's data)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          description: Page number
          schema:
            type: integer
            default: 1
            example: 1

        - in: query
          name: limit
          description: Number of records per page
          schema:
            type: integer
            default: 10
            example: 10

        - in: query
          name: search
          description: Search by paper name
          schema:
            type: string
            example: Maths

      responses:
        200:
          description: Paginated list of question papers

  /questions/{id}/questions:
    get:
      tags: [Question Papers]
      summary: Get questions of a question paper (owner only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Question Paper ID
          schema:
            type: integer

        - in: query
          name: page
          description: Page number
          schema:
            type: integer
            default: 1
            example: 1

        - in: query
          name: limit
          description: Number of records per page
          schema:
            type: integer
            default: 10
            example: 10

        - in: query
          name: search
          description: Search by question text
          schema:
            type: string
            example: addition

      responses:
        200:
          description: Paginated list of questions

  /questions/{id}:
    put:
      tags: [Question Papers]
      summary: Update question paper (only owner can update)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              paper_name: "Updated Paper"
              level_id: 2
              set_id: 3
              duration: 90
              paper_type: "practice"
              status: "inactive"
      responses:
        200:
          description: Updated successfully

    delete:
      tags: [Question Papers]
      summary: Delete question paper (only owner can delete)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deleted successfully

  /questions/question/{questionId}:
    put:
      tags: [Question Papers]
      summary: Update question (only owner can update)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: questionId
          required: true
          schema:
            type: integer
          description: Question ID
      requestBody:
        required: true
        content:
          application/json:
            example:
              section: "B"
              question_type: "mcq"
              marks: 2
              negative_marks: 0.5
              question: "Updated question?"
              option1: "A"
              option2: "B"
              option3: "C"
              option4: "D"
              correct_option: "option2"
              explanation: "Updated explanation"
      responses:
        200:
          description: Updated successfully

    delete:
      tags: [Question Papers]
      summary: Delete question (only owner can delete)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: questionId
          required: true
          schema:
            type: integer
          description: Question ID
      responses:
        200:
          description: Deleted successfully
    /questions/export:
  get:
    tags: [Question Papers]
    summary: Export all question papers
    parameters:
      - in: query
        name: search
        schema:
          type: string
          example: math
    responses:
      200:
        description: PDF exported

/questions/{id}/export:
  get:
    tags: [Question Papers]
    summary: Export a question paper with questions
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      - in: query
        name: search
        schema:
          type: string
          example: addition
    responses:
      200:
        description: PDF exported